language: python
python:
 - "2.7"
env:
 - DB=sqlite
 - DB=postgresql

#install deps
install: 
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage coveralls --use-mirrors
before_script:
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'DROP DATABASE IF EXISTS s2g;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'create database s2g;' -U postgres; fi"
script: 
  - coverage run --branch --omit="*/site-packages/*","*/src/*","*/migrations/*" ./manage.py test --settings=share2grandma.settings.travis
after_success:
  - coveralls