language: python
python:
 - "2.7"


#install deps
install: 
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage coveralls --use-mirrors
script: 
  - coverage run ./manage.py test --settings=share2grandma.settings.travis
after_success:
  - coveralls